show databases;
create database student;
create database employes;
create database production;
use database;
create table mark(machine integer,trs integer,acdc integer,stdid varchar(20));
create table studentdetailes(studid varchar(10),name varchar(15),dept varchar(20));
desc mark;
desc studentdetailes;
insert into mark values(80,85,90,"15bee218");
select * from marks;
inser into studentdetailes values("15bee218","rosith","eee");
select * from studentdetailes;
show tables;
use production;
create table items(items varchar(20),itemdesc varchar(25));
desc items;
alter table item add packege varchar (10);
desc items;
alter table items modify column itemid varchar(300);
desc items;
